// Player Edit State

enum (+=1)
{
	PLAYER_EDIT_NONE,
	PLAYER_EDIT_MOVE,
	PLAYER_EDIT_MASS_ADD_WALK,
	PLAYER_EDIT_MASS_ADD_CROSS,
	PLAYER_EDIT_MASS_ADD_FLEE,
	PLAYER_EDIT_MASS_ADD_JUMP,
	PLAYER_EDIT_MASS_ADD_TELE,
	PLAYER_EDIT_NODE_W,
	PLAYER_EDIT_NODE_H
};

enum E_PLAYER_EDIT
{
	pEditState,
	pEditSel,
	pLastShotStamp,
	Float:pLastShotVec[6]
};

new gPlayerEdit[MAX_PLAYERS][E_PLAYER_EDIT];