// Dialog IDs

enum (+=1)
{
	DID_NO_EFFECT = 22000,

	DID_PN_MAIN,
	DID_PN_NODE_OPT,
	DID_PN_NODE_CON_LIST,
	DID_PN_NODE_INFO,
	DID_PN_NODE_DESTROY,
	DID_PN_NODE_TYPE,
	DID_PN_NODE_INTERIOR,
	DID_PN_NODE_W,
	DID_PN_NODE_H
};