#define PEDS_MAP_MIN_X		-3000.0
#define PEDS_MAP_MIN_Y		-3000.0

#define PEDS_MAP_MAX_X		3000.0
#define PEDS_MAP_MAX_Y		3000.0

#define PEDS_MAP_SIZE_X		(PEDS_MAP_MAX_X - PEDS_MAP_MIN_X)
#define PEDS_MAP_SIZE_Y		(PEDS_MAP_MAX_Y - PEDS_MAP_MIN_Y)

#define PEDS_MAP_VX			(PEDS_MAP_SIZE_X / NUM_PED_ZONES_X)
#define PEDS_MAP_VY			(PEDS_MAP_SIZE_Y / NUM_PED_ZONES_Y)

new gZoneCount_Tele[NUM_PED_ZONES_X][NUM_PED_ZONES_Y];